### ISSUE TITLE
[Feat] 프로필 페이지 주소 변경

### ISSUE THREAD

**Issue by DayTeaJun** [FRONTENDSCHOOL5/final-04-fearless4#106]
## Description
각 프로필 페이지의 useParams로 라우터 세부주소 설정

## Todo
- [x] myProfile 페이지 라우터 세부주소 변경
- [x] userProfile 페이지 라우터 세부주소 변경
- [x] 각 컴포넌트에서 Link to 및 useNavigate를 이용한 주소 변경의 로직을 변경

## ETC
기타 사항
- post, follow, comment, search, bottomnav 등의 컴포넌트에서 porifle로 통하는 navigate를 변경 및 state를 보내지 않고,
- profile 페이지에서 useParams를 이용하여 어떤 유저의 프로필인지 확인할 수 있도록 변경함.
