### ISSUE TITLE
게시글 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by starcradle101** [FRONTENDSCHOOL5/final-04-fearless4#112]
## Description
게시글 컴포넌트 리팩토링을 진행하는 이슈입니다. 다음과 같은 문제를 개선해야 합니다:
* post.style.jsx 내부에 Post 컴포넌트와 스타일드 컴포넌트가 같이 존재합니다. 컴포넌트의 통일성을 위해서 분리해 주어야 합니다.
* Post 컴포넌트 내부에서 Axios로 API 요청을 보낼 때 headers가 중복되고 있습니다. 이를 최소화해야 합니다.
* 에러 핸들링 시 전체적으로 콘솔만 찍고 있는 상황입니다. 사용자가 분명히 상태를 확인할 수 있도록 모달 경고를 추가해야 합니다.

## Todo
- [x] post.style.jsx에서 Post 컴포넌트와 스타일드 컴포넌트 분리
- [x] 중복된 API 요청을 최소화
- [x] 컴포넌트 라우터 경로 수정
- [x] 에러 핸들링 시 콘솔을 찍는 대신 모달 경고를 추가

## ETC
