### ISSUE TITLE
[Refactor] 팔로우 페이지 리팩토링

### ISSUE THREAD

**Issue by DayTeaJun** [FRONTENDSCHOOL5/final-04-fearless4#115]
## Description
팔로우 페이지 렌더링 속도 향상 및 중복 코드 개선

## Todo
- [x] 팔로우 및 팔로잉의 중복 컴포넌트를 하나의 팔로우 컴포넌트로 통합
- [x] 팔로우 페이지를 useParams로만 데이터 받아오기
- [x] 팔로우 페이지 렌더링 속도 향상
- [x] 리액트 쿼리로 로직 변경
- [x] 팔로우 페이지 더보기 버튼 생성
- [x] 더보기 버튼을 무한스크롤로 변경
- [x] CSS 디자인 리팩토링
- [x] 팔로우 및 취소 버튼 렌더링 속도 개선
- [x] HTML 시맨틱 코드 사용
- [x] 중복 로직 최소화 작업
