### ISSUE TITLE
댓글 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by starcradle101** [FRONTENDSCHOOL5/final-04-fearless4#116]
## Description
댓글 컴포넌트와 관련된 리팩토링을 진행하는 이슈입니다.
다음과 같은 문제를 개선해야 합니다:
* 모바일 뷰에서 확인할 경우 댓글 게시 버튼이 찌그러집니다.
* 댓글 게시 버튼의 대비가 떨어집니다. 접근성을 고려해 수정해야 합니다.
* 댓글을 신고하거나 삭제하는 기능을 가진 메서드를 API로 따로 분리하면 좋을 것 같습니다.

## Todo
- [x] Comment.jsx 컴포넌트 위치를 Pages -> Component로 이동
- [x] 모바일 뷰에서 댓글 게시 버튼 수정
- [x] Comment.jsx 컴포넌트 API 수정
## ETC

**Comment by starcradle101** [comment]
해당 이슈는 이후 추가적인 hotfixes 브랜치에서 작업 예정입니다.
