### ISSUE TITLE
[Refactor] 프로필 페이지 리팩토링

### ISSUE THREAD

**Issue by DayTeaJun** [FRONTENDSCHOOL5/final-04-fearless4#119]
## Description
사용자 및 다른 유저 프로필 페이지 통합 및 useParams로 데이터 받아오기

## Todo
- [x] 사용자 및 다른 유저 프로필 통합
- [x] 사용자 프로필 수정시 state 받아오기
- [x] 다른 유저 프로필에서 팔로우 버튼 비정상적으로 크기가 바뀌는 현상 수정
- [x] 리액트 쿼리로 로직 변경
- [x] 프로필 렌더링 리액트 쿼리로 변경
- [x] api 폴더안에 axiosInstance 생성하여 중복 로직(header, url) 개선
- [x] profileAPI로 프로필 컴포넌트 API로직 코드 수 줄이기
- [x] 프로필 페이지 팔로우 렌더링 리액트 쿼리로 변경
- [x] 프로필 스타일드 컴포넌트명 userProfile -> profile 변경
- [x] 프로필 수정 페이지 리액트 쿼리로 변경
- [x] 프로필 페이지의 프로필 로직을 ProfileCard로 분리
- [x] 없는 유저의 프로필로 URL을 통해서 이동할 경우 404 보이게 개선
- [x] 팔로우 페이지 리액트 쿼리 변경 및 무한스크롤 로직 수정
- [x] 시맨틱 태그로 수정
