### ISSUE TITLE
[Refactor] hotfixes 전체적인 리팩토링

### ISSUE THREAD

**Issue by DayTeaJun** [FRONTENDSCHOOL5/final-04-fearless4#121]
## Description
부분 페이지별로 수정이 아닌, hotfixes 브랜치를 통한 전체적인 리팩토링

## Todo
- [x] 모바일에서 바텀네브바가 잘리는 현상 수정
- [x] 스크롤 상단으로 이동하는 탑버튼 생성
- [x] 각 navbar position relative로 변경 (반응형 고려) 및 전체 페이지 height 뷰포트값 수정
- [x] 상단 nav 시맨틱 태그 변경 및 버튼 이름 추가
- [x] 불필요한 index.css 삭제 (GlobalStyle.jsx 이용)
- [x] 프로필 편집 a태그 styled-components 새로 생성 -> ProfileEdit
- [x] 채팅페이지 콘솔 경고 해결 (styledComponent를 jsx함수 외부로 이동)
- [x] 채팅페이지 HTML/CSS UI 조금 수정
- [x] 404페이지 HTML/CSS 수정 (alt, 홈으로 돌아가기 버튼 안눌러지는 버그 수정)
- [x] asset image 크기들을 렌더링될 이미지만큼 줄이기
- [x] 회원가입 및 프로필편집 때 유효성 검사를 onBlur -> onChage로 변경하면서 debounce를 사용하여 변경
