### ISSUE TITLE
[Refactor] 검색페이지 리팩토링

### ISSUE THREAD

**Issue by sy412** [FRONTENDSCHOOL5/final-04-fearless4#130]
## Description
검색 페이지 UI 개선 및 리팩토링

## Todo
- [x] axiosInstance 사용
- [x] useQuery로 로직 변경
- [x] UI 개선
- [x] 더보기 기능 추가
- [x] 검색결과가 없을 때 결과가 없다는 메세지 띄우기
- [x] 검색중일때 로딩인디케이터 표시

## ETC
기타 사항
